[global]
dataFrameSerialization = "legacy"

[server]
maxUploadSize = 10
maxMessageSize = 10

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#667eea"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"